apiVersion: apps/v1
kind: Deployment
metadata:
  name: letskube-deployment
  labels:
    app: letskube
spec:
  replicas: 1
  template:
    metadata:
      name: letskube
      labels:
        app: letskube
      annotations:
        prometheus.io/scrape: 'true'
        filter.by.port.name: 'true'        
    spec:
      containers:
      - name: letskube
        image: kontacthimanshu/letsprometheus:v7
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: letskube

---

apiVersion: v1
kind: Service
metadata:
  name: letskube-service
  annotations:
           prometheus.io/scrape: 'true'
           filter.by.port.name: 'true'
spec:
  selector:
    app: letskube
  ports:
    - port: 80
  type: LoadBalancer
  
  